#!/bin/bash
set -e

# 1) 创建运行期角色（集群级，幂等）
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$do\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DH_PLATFORM_WRITER_USER}') THEN
    CREATE ROLE ${DH_PLATFORM_WRITER_USER} LOGIN PASSWORD '${DH_PLATFORM_WRITER_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DH_ANALYTICS_READER_USER}') THEN
    CREATE ROLE ${DH_ANALYTICS_READER_USER} LOGIN PASSWORD '${DH_ANALYTICS_READER_PASSWORD}';
  END IF;
END \$do\$;
EOSQL

# 2) 创建双逻辑数据库并收紧连接权限（第二道边界）
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
CREATE DATABASE ${DH_PLATFORM_DB};
CREATE DATABASE ${DH_ANALYTICS_DB};
REVOKE CONNECT ON DATABASE ${DH_PLATFORM_DB} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${DH_PLATFORM_DB} TO ${DH_PLATFORM_WRITER_USER};
REVOKE CONNECT ON DATABASE ${DH_ANALYTICS_DB} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${DH_ANALYTICS_DB} TO ${DH_ANALYTICS_READER_USER};
EOSQL
