#!/bin/bash
set -euo pipefail

PLATFORM_USER="${PLATFORM_USER:-platform_app}"
PLATFORM_PASSWORD="${PLATFORM_PASSWORD:-platform}"
ANALYTICS_OWNER_USER="${ANALYTICS_OWNER_USER:-analytics_owner}"
ANALYTICS_OWNER_PASSWORD="${ANALYTICS_OWNER_PASSWORD:-owner}"
ANALYTICS_READER_USER="${ANALYTICS_READER_USER:-analytics_reader}"
ANALYTICS_READER_PASSWORD="${ANALYTICS_READER_PASSWORD:-reader}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
SELECT 'CREATE DATABASE platform' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'platform')\gexec
SELECT 'CREATE DATABASE analytics' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'analytics')\gexec

REVOKE CONNECT ON DATABASE platform FROM PUBLIC;
REVOKE CONNECT ON DATABASE analytics FROM PUBLIC;
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${PLATFORM_USER}') THEN
    CREATE ROLE ${PLATFORM_USER} LOGIN PASSWORD '${PLATFORM_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${ANALYTICS_OWNER_USER}') THEN
    CREATE ROLE ${ANALYTICS_OWNER_USER} LOGIN PASSWORD '${ANALYTICS_OWNER_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${ANALYTICS_READER_USER}') THEN
    CREATE ROLE ${ANALYTICS_READER_USER} LOGIN PASSWORD '${ANALYTICS_READER_PASSWORD}';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE platform TO ${PLATFORM_USER};
GRANT CONNECT, CREATE ON DATABASE analytics TO ${ANALYTICS_OWNER_USER};
GRANT CONNECT ON DATABASE analytics TO ${ANALYTICS_READER_USER};
REVOKE CONNECT ON DATABASE analytics FROM ${PLATFORM_USER};
REVOKE CONNECT ON DATABASE platform FROM ${ANALYTICS_OWNER_USER};
REVOKE CONNECT ON DATABASE platform FROM ${ANALYTICS_READER_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname platform <<SQL
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO ${PLATFORM_USER};
ALTER SCHEMA public OWNER TO ${PLATFORM_USER};
REVOKE TEMP ON DATABASE platform FROM PUBLIC;
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname analytics <<SQL
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE TEMP ON DATABASE analytics FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS analytics AUTHORIZATION ${ANALYTICS_OWNER_USER};
GRANT USAGE ON SCHEMA analytics TO ${ANALYTICS_READER_USER};
ALTER ROLE ${ANALYTICS_READER_USER} IN DATABASE analytics SET search_path = analytics;
ALTER ROLE ${ANALYTICS_READER_USER} IN DATABASE analytics SET default_transaction_read_only = on;
SQL
